<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

namespace Sindri\Generator\Ast\Queue;

use Override;
use PhpParser\Node\Expr;
use PhpParser\PrettyPrinter\Standard;
use PhpParser\PrettyPrinterAbstract;
use Sindri\Generator\Abstract\AstFileGenerator;
use Sindri\Generator\Enum\GenerateStatus;
use Sindri\Generator\Queue\Contract\QueueDataFileGeneratorContract;
use Valkyrja\Queue\Routing\Data\Contract\RouteContract;
use Valkyrja\Queue\Routing\Data\QueueRoutingData;

class AstQueueDataFileGenerator extends AstFileGenerator implements QueueDataFileGeneratorContract
{
    public function __construct(
        protected PrettyPrinterAbstract $printer = new Standard(),
    ) {
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFile(
        string $directory,
        string $className,
        string $namespace,
        array $routes,
    ): GenerateStatus {
        return $this->writeFile($directory, $className, $this->generateFileContents($namespace, $className, $routes));
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(array $routes): string
    {
        $dataNamespace = 'Sindri\Queue\Data\QueueRoutingData';
        $routesContent = $this->getRoutesAsContent($routes);

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                routes: $routesContent,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * @param non-empty-string    $namespace
     * @param non-empty-string    $className
     * @param array<string, Expr> $routes
     *
     * @return non-empty-string
     */
    protected function generateFileContents(string $namespace, string $className, array $routes): string
    {
        $routingData   = QueueRoutingData::class;
        $routesContent = $this->getRoutesAsContent($routes);

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $routingData;

            final readonly class $className extends QueueRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: $routesContent,
                    );
                }
            }

            PHP;
    }

    /**
     * Pretty-print all routes into a PHP array literal string.
     *
     * @param array<string, Expr> $routes
     *
     * @return non-empty-string
     */
    protected function getRoutesAsContent(array $routes): string
    {
        $routeContract = RouteContract::class;
        $routesContent = '';

        foreach ($routes as $key => $routeExpr) {
            $keyPhp         = $this->printer->prettyPrintExpr($this->buildEnumCaseExpr($key));
            $routePhp       = $this->printer->prettyPrintExpr($routeExpr);
            $routesContent .= <<<PHP
                $keyPhp => static fn (): \\$routeContract => $routePhp,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }
}
