<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

namespace Sindri\Generator\Ast\Http;

use Closure;
use Override;
use PhpParser\Node\Arg;
use PhpParser\Node\ArrayItem;
use PhpParser\Node\Expr;
use PhpParser\Node\Expr\Array_;
use PhpParser\Node\Expr\New_;
use PhpParser\Node\Identifier;
use PhpParser\Node\Scalar\String_;
use PhpParser\PrettyPrinter\Standard;
use PhpParser\PrettyPrinterAbstract;
use Sindri\Ast\Data\HttpParameterData;
use Sindri\Ast\Data\HttpRouteData;
use Sindri\Generator\Abstract\AstFileGenerator;
use Sindri\Generator\Enum\GenerateStatus;
use Sindri\Generator\Http\Contract\HttpDataFileGeneratorContract;
use Sindri\Generator\Throwable\Exception\GeneratorUnreachableException;
use Valkyrja\Http\Message\Enum\RequestMethod;
use Valkyrja\Http\Routing\Data\Contract\RouteContract;
use Valkyrja\Http\Routing\Data\DynamicRoute;
use Valkyrja\Http\Routing\Data\HttpRoutingData;
use Valkyrja\Http\Routing\Data\Parameter;
use Valkyrja\Http\Routing\Processor\Contract\ProcessorContract;
use Valkyrja\Http\Routing\Processor\Processor;

use function array_map;
use function constant;
use function defined;
use function in_array;
use function str_contains;
use function strrpos;
use function substr;
use function trim;

/**
 * AST-based HTTP routing data file generator.
 *
 * Accepts PHP-Parser Expr nodes produced by HttpRouteAttributeReader and the
 * plain HttpRouteData objects used to derive paths, dynamicPaths, and regexes.
 */
class AstHttpDataFileGenerator extends AstFileGenerator implements HttpDataFileGeneratorContract
{
    public function __construct(
        protected PrettyPrinterAbstract $printer = new Standard(),
        protected ProcessorContract $processor = new Processor(),
    ) {
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFile(
        string $directory,
        string $className,
        string $namespace,
        array $routes,
        array $routeData,
    ): GenerateStatus {
        return $this->writeFile($directory, $className, $this->generateFileContents($namespace, $className, $routes, $routeData));
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(array $routes, array $routeData): string
    {
        $dataNamespace = HttpRoutingData::class;
        $routesContent = $this->getRoutesAsContent($routes, $routeData);

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                routes: $routesContent,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * @param non-empty-string             $namespace
     * @param non-empty-string             $className
     * @param array<string, Expr>          $routes
     * @param array<string, HttpRouteData> $routeData
     *
     * @return non-empty-string
     */
    protected function generateFileContents(
        string $namespace,
        string $className,
        array $routes,
        array $routeData,
    ): string {
        $routingData   = HttpRoutingData::class;
        $routesContent = $this->getRoutesAsContent($routes, $routeData);
        $paths         = $this->printer->prettyPrintExpr($this->buildNestedStringArrayExpr($this->buildPaths($routeData)));
        $dynamicPaths  = $this->printer->prettyPrintExpr($this->buildNestedStringArrayExpr($this->buildDynamicPaths($routeData)));
        $regexes       = $this->printer->prettyPrintExpr($this->buildNestedStringArrayExpr($this->buildRegexes($routeData)));

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $routingData;

            final readonly class $className extends HttpRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: $routesContent,
                        paths: $paths,
                        dynamicPaths: $dynamicPaths,
                        regexes: $regexes,
                    );
                }
            }

            PHP;
    }

    /**
     * Build the paths map: method → path → route name (static routes only).
     *
     * @param array<string, HttpRouteData> $routeData
     *
     * @return array<string, array<string, string>>
     */
    protected function buildPaths(array $routeData): array
    {
        $paths = [];

        foreach ($routeData as $name => $data) {
            if ($data->isDynamic) {
                continue;
            }

            $path = $this->normalizePath($data->path);

            foreach ($this->extractMethodNames($data->requestMethods) as $method) {
                $paths[$method][$path] = $name;
            }
        }

        return $paths;
    }

    /**
     * Build the dynamicPaths map: method → path → route name (dynamic routes only).
     *
     * @param array<string, HttpRouteData> $routeData
     *
     * @return array<string, array<string, string>>
     */
    protected function buildDynamicPaths(array $routeData): array
    {
        $dynamicPaths = [];

        foreach ($routeData as $name => $data) {
            if (! $data->isDynamic) {
                continue;
            }

            $path = $this->normalizePath($data->path);

            foreach ($this->extractMethodNames($data->requestMethods) as $method) {
                $dynamicPaths[$method][$path] = $name;
            }
        }

        return $dynamicPaths;
    }

    /**
     * Build the regexes map: method → regex → route name (dynamic routes only).
     *
     * @param array<string, HttpRouteData> $routeData
     *
     * @return array<string, array<string, string>>
     */
    protected function buildRegexes(array $routeData): array
    {
        $regexes = [];

        foreach ($routeData as $name => $data) {
            if (! $data->isDynamic || $data->parameters === []) {
                continue;
            }

            $regex = $this->computeRegex($data);

            if ($regex === '') {
                continue;
            }

            foreach ($this->extractMethodNames($data->requestMethods) as $method) {
                $regexes[$method][$regex] = $name;
            }
        }

        return $regexes;
    }

    /**
     * Build a nested string array expression: array<string, array<string, string>> → Array_ AST node.
     *
     * @param array<string, array<string, string>> $data
     */
    protected function buildNestedStringArrayExpr(array $data): Array_
    {
        $outerItems = [];

        foreach ($data as $outerKey => $innerMap) {
            $innerItems = [];

            foreach ($innerMap as $innerKey => $value) {
                $innerItems[] = new ArrayItem($this->buildEnumCaseExpr($value), new String_($innerKey));
            }

            $outerItems[] = new ArrayItem(new Array_($innerItems), new String_($outerKey));
        }

        return new Array_($outerItems);
    }

    /**
     * Compute the regex for a dynamic route by running it through the Processor.
     */
    protected function computeRegex(HttpRouteData $data): string
    {
        $parameters = [];

        foreach ($data->parameters as $param) {
            $parameters[] = $this->buildParameter($param);
        }

        $route = new DynamicRoute(
            path: $data->path !== '' ? $data->path : '/',
            name: $data->name !== '' ? $data->name : 'temp',
            regex: '',
            parameters: $parameters,
            handler: $this->unreachableRouteHandler(),
        );

        $processed = $this->processor->route($route);

        if ($processed instanceof DynamicRoute) {
            return $processed->getRegex();
        }

        return '';
    }

    /**
     * Placeholder handler for the temporary route used only to compute a regex.
     *
     * The route is never dispatched, so this handler is never invoked in production;
     * it exists solely to satisfy DynamicRoute::__construct().
     *
     * @return Closure(): never
     */
    protected function unreachableRouteHandler(): Closure
    {
        return static fn (): never => throw new GeneratorUnreachableException('unreachable');
    }

    /**
     * Convert an HttpParameterData into a Parameter data object.
     *
     * When the regex is a class-constant reference like "Vendor\Regex::ALPHA", resolve it
     * to its actual string value so the Processor can compute the correct route regex.
     */
    protected function buildParameter(HttpParameterData $data): Parameter
    {
        $regex = $data->regex;

        if (str_contains($regex, '::') && defined($regex)) {
            /** @var string $resolved */
            $resolved = constant($regex);

            if ($resolved !== '') {
                $regex = $resolved;
            }
        }

        return new Parameter(
            name: $data->name,
            regex: $regex,
            isOptional: $data->isOptional,
            shouldCapture: $data->shouldCapture,
        );
    }

    /**
     * Normalize a route path: ensure a leading slash and strip trailing slashes.
     */
    protected function normalizePath(string $path): string
    {
        return '/' . trim($path, '/');
    }

    /**
     * Extract HTTP method name strings from "FQN::CASE" enum strings.
     *
     * A route registered for any request method is expanded to every concrete method,
     * and is never keyed under a literal `ANY`, mirroring how the framework's
     * RouteCollection registers it at runtime. Without that expansion a cached route
     * declared for ANY would never be matched, since a request always carries a
     * concrete method.
     *
     * @param string[] $requestMethods
     *
     * @return string[]
     */
    protected function extractMethodNames(array $requestMethods): array
    {
        $methods = [];

        foreach ($requestMethods as $method) {
            $pos = strrpos($method, '::');

            if ($pos !== false) {
                $methods[] = substr($method, $pos + 2);
            }
        }

        if (in_array(RequestMethod::ANY->value, $methods, true)) {
            return array_map(
                static fn (RequestMethod $requestMethod): string => $requestMethod->value,
                RequestMethod::all()
            );
        }

        return $methods;
    }

    /**
     * Pretty-print all routes into a PHP array literal string.
     *
     * For DynamicRoute expressions, injects the Processor-computed regex as a named arg
     * because DynamicRoute::__construct() requires it.
     *
     * @param array<string, Expr>          $routes
     * @param array<string, HttpRouteData> $routeData
     *
     * @return non-empty-string
     */
    protected function getRoutesAsContent(array $routes, array $routeData): string
    {
        $routeContract = RouteContract::class;
        $routesContent = '';

        foreach ($routes as $key => $routeExpr) {
            $data = $routeData[$key] ?? null;

            if ($data !== null && $data->isDynamic && $routeExpr instanceof New_) {
                $computedRegex     = $data->parameters !== [] ? $this->computeRegex($data) : '';
                $routeExpr         = clone $routeExpr;
                $routeExpr->args[] = new Arg(
                    value: new String_($computedRegex),
                    name: new Identifier('regex'),
                );
            }

            $keyPhp         = $this->printer->prettyPrintExpr($this->buildEnumCaseExpr($key));
            $routePhp       = $this->printer->prettyPrintExpr($routeExpr);
            $routesContent .= <<<PHP
                $keyPhp => static fn (): \\$routeContract => $routePhp,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }
}
