<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

namespace Sindri\Generator\Ast\Event;

use Override;
use PhpParser\Node\Expr;
use PhpParser\PrettyPrinter\Standard;
use PhpParser\PrettyPrinterAbstract;
use Sindri\Generator\Abstract\AstFileGenerator;
use Sindri\Generator\Enum\GenerateStatus;
use Sindri\Generator\Event\Contract\EventDataFileGeneratorContract;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\EventData;

/**
 * AST-based event data file generator.
 *
 * Accepts PHP-Parser Expr nodes produced by ListenerAttributeReader and pretty-prints
 * them directly into the generated data class, bypassing any runtime app boot.
 */
class AstEventDataFileGenerator extends AstFileGenerator implements EventDataFileGeneratorContract
{
    public function __construct(
        protected PrettyPrinterAbstract $printer = new Standard(),
    ) {
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFile(
        string $directory,
        string $className,
        string $namespace,
        array $listeners,
    ): GenerateStatus {
        return $this->writeFile($directory, $className, $this->generateFileContents($namespace, $className, $listeners));
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(array $listeners): string
    {
        $dataNamespace    = EventData::class;
        $listenersContent = $this->getListenersAsContent($listeners);

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                events: [],
                listeners: $listenersContent,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * @param non-empty-string    $namespace
     * @param non-empty-string    $className
     * @param array<string, Expr> $listeners
     *
     * @return non-empty-string
     */
    protected function generateFileContents(string $namespace, string $className, array $listeners): string
    {
        $eventData        = EventData::class;
        $listenersContent = $this->getListenersAsContent($listeners);

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $eventData;

            final readonly class $className extends EventData
            {
                public function __construct()
                {
                    parent::__construct(
                        events: [],
                        listeners: $listenersContent,
                    );
                }
            }

            PHP;
    }

    /**
     * Pretty-print all listeners into a PHP array literal string.
     *
     * @param array<string, Expr> $listeners
     *
     * @return non-empty-string
     */
    protected function getListenersAsContent(array $listeners): string
    {
        $listenerContract = ListenerContract::class;
        $listenersContent = '';

        foreach ($listeners as $key => $listenerExpr) {
            $listenerPhp       = $this->printer->prettyPrintExpr($listenerExpr);
            $listenersContent .= <<<PHP
                '$key' => static fn (): \\$listenerContract => $listenerPhp,

                PHP;
        }

        return <<<PHP
            [
                $listenersContent
            ]
            PHP;
    }
}
