<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sindri\Generator\Ast\Container;

use Override;
use Sindri\Generator\Abstract\AstFileGenerator;
use Sindri\Generator\Container\Contract\ContainerDataFileGeneratorContract;
use Sindri\Generator\Enum\GenerateStatus;
use Valkyrja\Container\Data\ContainerData;

/**
 * AST-based container data file generator.
 *
 * Accepts the publishers map extracted by ServiceProviderReader and emits
 * a ContainerData subclass using ::class syntax rather than string literals,
 * bypassing any runtime app boot.
 *
 * Only callbacks is populated; the provider list is managed by the app config.
 */
class AstContainerDataFileGenerator extends AstFileGenerator implements ContainerDataFileGeneratorContract
{
    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFile(
        string $directory,
        string $className,
        string $namespace,
        array $publishers,
    ): GenerateStatus {
        return $this->writeFile($directory, $className, $this->generateFileContents($namespace, $className, $publishers));
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(array $publishers): string
    {
        $dataNamespace    = ContainerData::class;
        $callbacks = $this->getCallbackContent($publishers);

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                callbacks: $callbacks,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * @param non-empty-string                                       $namespace
     * @param non-empty-string                                       $className
     * @param array<class-string, array{0: class-string, 1: string}> $publishers
     *
     * @return non-empty-string
     */
    protected function generateFileContents(string $namespace, string $className, array $publishers): string
    {
        $containerData    = ContainerData::class;
        $callbacks = $this->getCallbackContent($publishers);

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $containerData;

            final readonly class $className extends ContainerData
            {
                public function __construct()
                {
                    parent::__construct(
                        callbacks: $callbacks,
                    );
                }
            }

            PHP;
    }

    /**
     * Pretty-print all publisher entries as a PHP array literal using ::class syntax.
     *
     * @param array<class-string, array{0: class-string, 1: string}> $publishers
     *
     * @return non-empty-string
     */
    protected function getCallbackContent(array $publishers): string
    {
        $content = '';

        foreach ($publishers as $serviceClass => [$providerClass, $method]) {
            $content .= <<<PHP
                \\$serviceClass::class => [\\$providerClass::class, '$method'],

                PHP;
        }

        return <<<PHP
            [
                $content]
            PHP;
    }
}
